server:
  port: 8502

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
